[technote]
id = "DMTN-327"
series_id = "DMTN"
canonical_url = "https://dmtn-327.lsst.io"
github_url = "https://github.com/lsst-dm/dmtn-327"
github_default_branch = "main"
date_created = 2025-10-08T22:24:35Z
organization.name = "NSF-DOE Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "stable"

[[technote.authors]]
name.given = "Ross"
name.family = "Ceballo"
internal_id = "ceballor"
orcid = "https://orcid.org/0009-0000-9679-3911"
[[technote.authors.affiliations]]
name = "NSF NOIRLab"
internal_id = "RubinOps"
address = "Tucson"

[[technote.authors]]
name.given = "Arianna"
name.family = "Ranabhat"
internal_id = "ranabhata"
orcid = "https://orcid.org/0000-0002-6112-9778"
[[technote.authors.affiliations]]
name = "Macquarie University"
internal_id = "AAO"
address = "North Ryde"
